Add hacbs-jdk7-builder
redhat-appstudio/jvm-build-service-builder-images pull request #9
Opened 2022-10-28 01:34 UTC by dwalluck

2022-10-28 05:18 UTC, stuartwdouglas requested changes
This also needs an entry in https://github.com/redhat-appstudio/jvm-build-service-builder-images/blob/main/image-config.yaml

2022-10-31 20:44 UTC, merged

2022-10-31 20:46 UTC, stuartwdouglas commented
Merged, thanks. @dwalluck do you want to update the main repo to use this? You will need to update the builder images sha (I think in a few different places), and add a new entry for this image in the system config yaml.

There may also be a few places that assume JDK 1.8 is the lowest, so that may also need some fixes.

2022-10-31 23:13 UTC, dwalluck commented
> Merged, thanks. @dwalluck do you want to update the main repo to use this? You will need to update the builder images sha (I think in a few different places), and add a new entry for this image in the system config yaml.
> 
> There may also be a few places that assume JDK 1.8 is the lowest, so that may also need some fixes.

I will look into it.

2022-11-02 21:23 UTC, dwalluck commented
> There may also be a few places that assume JDK 1.8 is the lowest, so that may also need some fixes.

Yes, min JDK is set to 8 in a couple places. I assume in terms of priority that JDK 7 should come last, though.

Do you need to upload the image to the official quay repository before I create a PR for main>

2022-11-03 09:34 UTC, stuartwdouglas commented on .tekton/hacbs-jdk7-builder-pull-request.yaml
> +      value: "quay.io/redhat-appstudio/pull-request-builds:hacbs-jdk7-builder-{{revision}}"
@Michkov can you create this repo please? I don't seem to have permission.

2022-11-03 09:34 UTC, stuartwdouglas commented on .tekton/hacbs-jdk7-builder-push.yaml
> +      value: 'quay.io/redhat-appstudio/hacbs-jdk7-builder:{{revision}}'
@Michkov oops, I mean this repo.

2022-11-03 09:34 UTC, stuartwdouglas commented on .tekton/hacbs-jdk7-builder-pull-request.yaml
> +      value: "quay.io/redhat-appstudio/pull-request-builds:hacbs-jdk7-builder-{{revision}}"
oops, I actually mean the repo below, not this one.